version: '3'
services:
  ui:
    build: ../camp-ui/
    restart: always
    working_dir: "/var/www/camp-ui"
    # command: ["bash", "-c", "npm install && npm run dev"]
    environment:
      TZ: Asia/Tokyo
    tty: true
    volumes:
      - ${UI_DIR}:/var/www/camp-ui
      - nodemodules:/var/www/camp-ui/node_modules
    ports:
      - "5173:5173"
  api:
    build: ../camp-api/
    restart: always
    working_dir: "/var/www/camp-api"
    # command: ["bash", "-c", "go mod download && go mod verify"]
    environment:
      TZ: Asia/Tokyo
    tty: true
    volumes:
      - ${API_DIR}:/var/www/camp-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4_unicode_ci
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql:
  nodemodules: